server:
  port: 9091
# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
  #指定应用名称，将来会作为服务的id使用
  application:
    name: user-service
# mybatis 別名包扫描
mybatis:
  type-aliases-package: com.liuyujie.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka